// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHubTodoDemo.GitHub.Repos.Item.Item.Pulls.Item.Reviews.Item.Dismissals {
    public enum DismissalsPutRequestBody_event {
        [EnumMember(Value = "DISMISS")]
        DISMISS,
    }
}
