version: 2
updates:
  - package-ecosystem: nuget
    directory: "/dotnet"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      kiota-dependencies:
        patterns:
          - "*kiota*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/java"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      kiota-dependencies:
        patterns:
          - "*kiota*"
      open-telemetry:
        patterns:
          - "*opentelemetry*"

  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      kiota-dependencies:
        patterns:
          - "*kiota*"
      open-telemetry:
        patterns:
          - "*opentelemetry*"
      pylint:
        patterns:
          - "*pylint*"
          - "*astroid*"

  - package-ecosystem: npm
    directory: "/typescript"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      kiota-dependencies:
        patterns:
          - "*kiota*"
      open-telemetry:
        patterns:
          - "*opentelemetry*"
