version: 2
updates:
- package-ecosystem: nuget
  directory: "/dotnet"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/java"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
