from enum import Enum


class AuthorAssociation(str, Enum):
    COLLABORATOR = "COLLABORATOR",
    CONTRIBUTOR = "CONTRIBUTOR",
    FIRST_TIMER = "FIRST_TIMER",
    FIRST_TIME_CONTRIBUTOR = "FIRST_TIME_CONTRIBUTOR",
    MANNEQUIN = "MANNEQUIN",
    MEMBER = "MEMBER",
    NONE_ = "NONE",
    OWNER = "OWNER",
