// <auto-generated/>
#pragma warning disable CS0618
using GitHubTodoDemo.MicrosoftGraph.Me.Todo;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHubTodoDemo.MicrosoftGraph.Me
{
    /// <summary>
    /// Builds and executes requests for operations under \me
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The todo property</summary>
        public global::GitHubTodoDemo.MicrosoftGraph.Me.Todo.TodoRequestBuilder Todo
        {
            get => new global::GitHubTodoDemo.MicrosoftGraph.Me.Todo.TodoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHubTodoDemo.MicrosoftGraph.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHubTodoDemo.MicrosoftGraph.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
