// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHubTodoDemo.GitHub.Repos.Item.Item.Pulls {
    public enum GetDirectionQueryParameterType {
        [EnumMember(Value = "asc")]
        Asc,
        [EnumMember(Value = "desc")]
        Desc,
    }
}
