// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHubTodoDemo.GitHub.Repos.Item.Item.Pulls {
    public enum GetStateQueryParameterType {
        [EnumMember(Value = "open")]
        Open,
        [EnumMember(Value = "closed")]
        Closed,
        [EnumMember(Value = "all")]
        All,
    }
}
