// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHubTodoDemo.GitHub.Repos.Item.Item.Pulls {
    public enum GetSortQueryParameterType {
        [EnumMember(Value = "created")]
        Created,
        [EnumMember(Value = "updated")]
        Updated,
        [EnumMember(Value = "popularity")]
        Popularity,
        [EnumMember(Value = "long-running")]
        LongRunning,
    }
}
