/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PullsRequestBuilderRequestsMetadata, type PullsRequestBuilder } from './pulls/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /repos/{owner}/{repo}
 */
export interface WithRepoItemRequestBuilder extends BaseRequestBuilder<WithRepoItemRequestBuilder> {
    /**
     * The pulls property
     */
    get pulls(): PullsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithRepoItemRequestBuilderUriTemplate = "{+baseurl}/repos/{owner}/{repo}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithRepoItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithRepoItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    pulls: {
        requestsMetadata: PullsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
