/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ReposRequestBuilderNavigationMetadata, type ReposRequestBuilder } from './repos/index.js';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BackingStoreFactory, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Instantiates a new {@link GitHubClient} and sets the default values.
 * @param backingStore The backing store to use for the models.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createGitHubClient(requestAdapter: RequestAdapter, backingStore?: BackingStoreFactory | undefined) {
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://api.github.com";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    requestAdapter.enableBackingStore(backingStore);
    return apiClientProxifier<GitHubClient>(requestAdapter, pathParameters, GitHubClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface GitHubClient extends BaseRequestBuilder<GitHubClient> {
    /**
     * The repos property
     */
    get repos(): ReposRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GitHubClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GitHubClientNavigationMetadata: Record<Exclude<keyof GitHubClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    repos: {
        navigationMetadata: ReposRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
