// <auto-generated/>
#pragma warning disable CS0618
using GitHubTodoDemo.MicrosoftGraph.Me.Todo.Lists.Item.Tasks;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHubTodoDemo.MicrosoftGraph.Me.Todo.Lists.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \me\todo\lists\{todoTaskList-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TodoTaskListItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Provides operations to manage the tasks property of the microsoft.graph.todoTaskList entity.</summary>
        public global::GitHubTodoDemo.MicrosoftGraph.Me.Todo.Lists.Item.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::GitHubTodoDemo.MicrosoftGraph.Me.Todo.Lists.Item.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHubTodoDemo.MicrosoftGraph.Me.Todo.Lists.Item.TodoTaskListItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TodoTaskListItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/todo/lists/{todoTaskList%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHubTodoDemo.MicrosoftGraph.Me.Todo.Lists.Item.TodoTaskListItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TodoTaskListItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/todo/lists/{todoTaskList%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
