// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHubTodoDemo.MicrosoftGraph.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TodoTask : global::GitHubTodoDemo.MicrosoftGraph.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A collection of file attachments for the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentBase>? Attachments { get; set; }
#nullable restore
#else
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentBase> Attachments { get; set; }
#endif
        /// <summary>The attachmentSessions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentSession>? AttachmentSessions { get; set; }
#nullable restore
#else
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentSession> AttachmentSessions { get; set; }
#endif
        /// <summary>The task body that typically contains information about the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHubTodoDemo.MicrosoftGraph.Models.ItemBody? Body { get; set; }
#nullable restore
#else
        public global::GitHubTodoDemo.MicrosoftGraph.Models.ItemBody Body { get; set; }
#endif
        /// <summary>The date and time when the task body was last modified. By default, it is in UTC. You can provide a custom time zone in the request header. The property value uses ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2020 would look like this: &apos;2020-01-01T00:00:00Z&apos;.</summary>
        public DateTimeOffset? BodyLastModifiedDateTime { get; set; }
        /// <summary>The categories associated with the task. Each category corresponds to the displayName property of an outlookCategory that the user has defined.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Categories { get; set; }
#nullable restore
#else
        public List<string> Categories { get; set; }
#endif
        /// <summary>A collection of checklistItems linked to a task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.ChecklistItem>? ChecklistItems { get; set; }
#nullable restore
#else
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.ChecklistItem> ChecklistItems { get; set; }
#endif
        /// <summary>The date and time in the specified time zone that the task was finished.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone? CompletedDateTime { get; set; }
#nullable restore
#else
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone CompletedDateTime { get; set; }
#endif
        /// <summary>The date and time when the task was created. By default, it is in UTC. You can provide a custom time zone in the request header. The property value uses ISO 8601 format. For example, midnight UTC on Jan 1, 2020 would look like this: &apos;2020-01-01T00:00:00Z&apos;.</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>The date and time in the specified time zone that the task is to be finished.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone? DueDateTime { get; set; }
#nullable restore
#else
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone DueDateTime { get; set; }
#endif
        /// <summary>The collection of open extensions defined for the task. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.Extension>? Extensions { get; set; }
#nullable restore
#else
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.Extension> Extensions { get; set; }
#endif
        /// <summary>Indicates whether the task has attachments.</summary>
        public bool? HasAttachments { get; set; }
        /// <summary>The importance property</summary>
        public global::GitHubTodoDemo.MicrosoftGraph.Models.Importance? Importance { get; set; }
        /// <summary>Set to true if an alert is set to remind the user of the task.</summary>
        public bool? IsReminderOn { get; set; }
        /// <summary>The date and time when the task was last modified. By default, it is in UTC. You can provide a custom time zone in the request header. The property value uses ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2020 would look like this: &apos;2020-01-01T00:00:00Z&apos;.</summary>
        public DateTimeOffset? LastModifiedDateTime { get; set; }
        /// <summary>A collection of resources linked to the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.LinkedResource>? LinkedResources { get; set; }
#nullable restore
#else
        public List<global::GitHubTodoDemo.MicrosoftGraph.Models.LinkedResource> LinkedResources { get; set; }
#endif
        /// <summary>The recurrence pattern for the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHubTodoDemo.MicrosoftGraph.Models.PatternedRecurrence? Recurrence { get; set; }
#nullable restore
#else
        public global::GitHubTodoDemo.MicrosoftGraph.Models.PatternedRecurrence Recurrence { get; set; }
#endif
        /// <summary>The date and time in the specified time zone for a reminder alert of the task to occur.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone? ReminderDateTime { get; set; }
#nullable restore
#else
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone ReminderDateTime { get; set; }
#endif
        /// <summary>The date and time in the specified time zone at which the task is scheduled to start.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone? StartDateTime { get; set; }
#nullable restore
#else
        public global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone StartDateTime { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::GitHubTodoDemo.MicrosoftGraph.Models.TaskStatus? Status { get; set; }
        /// <summary>A brief description of the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHubTodoDemo.MicrosoftGraph.Models.TodoTask"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::GitHubTodoDemo.MicrosoftGraph.Models.TodoTask CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHubTodoDemo.MicrosoftGraph.Models.TodoTask();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "attachmentSessions", n => { AttachmentSessions = n.GetCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentSession>(global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentSession.CreateFromDiscriminatorValue)?.AsList(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentBase>(global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "body", n => { Body = n.GetObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.ItemBody>(global::GitHubTodoDemo.MicrosoftGraph.Models.ItemBody.CreateFromDiscriminatorValue); } },
                { "bodyLastModifiedDateTime", n => { BodyLastModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "categories", n => { Categories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "checklistItems", n => { ChecklistItems = n.GetCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.ChecklistItem>(global::GitHubTodoDemo.MicrosoftGraph.Models.ChecklistItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "completedDateTime", n => { CompletedDateTime = n.GetObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>(global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "dueDateTime", n => { DueDateTime = n.GetObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>(global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "extensions", n => { Extensions = n.GetCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.Extension>(global::GitHubTodoDemo.MicrosoftGraph.Models.Extension.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hasAttachments", n => { HasAttachments = n.GetBoolValue(); } },
                { "importance", n => { Importance = n.GetEnumValue<global::GitHubTodoDemo.MicrosoftGraph.Models.Importance>(); } },
                { "isReminderOn", n => { IsReminderOn = n.GetBoolValue(); } },
                { "lastModifiedDateTime", n => { LastModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "linkedResources", n => { LinkedResources = n.GetCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.LinkedResource>(global::GitHubTodoDemo.MicrosoftGraph.Models.LinkedResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "recurrence", n => { Recurrence = n.GetObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.PatternedRecurrence>(global::GitHubTodoDemo.MicrosoftGraph.Models.PatternedRecurrence.CreateFromDiscriminatorValue); } },
                { "reminderDateTime", n => { ReminderDateTime = n.GetObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>(global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "startDateTime", n => { StartDateTime = n.GetObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>(global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::GitHubTodoDemo.MicrosoftGraph.Models.TaskStatus>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentBase>("attachments", Attachments);
            writer.WriteCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.AttachmentSession>("attachmentSessions", AttachmentSessions);
            writer.WriteObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.ItemBody>("body", Body);
            writer.WriteDateTimeOffsetValue("bodyLastModifiedDateTime", BodyLastModifiedDateTime);
            writer.WriteCollectionOfPrimitiveValues<string>("categories", Categories);
            writer.WriteCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.ChecklistItem>("checklistItems", ChecklistItems);
            writer.WriteObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>("completedDateTime", CompletedDateTime);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>("dueDateTime", DueDateTime);
            writer.WriteCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.Extension>("extensions", Extensions);
            writer.WriteBoolValue("hasAttachments", HasAttachments);
            writer.WriteEnumValue<global::GitHubTodoDemo.MicrosoftGraph.Models.Importance>("importance", Importance);
            writer.WriteBoolValue("isReminderOn", IsReminderOn);
            writer.WriteDateTimeOffsetValue("lastModifiedDateTime", LastModifiedDateTime);
            writer.WriteCollectionOfObjectValues<global::GitHubTodoDemo.MicrosoftGraph.Models.LinkedResource>("linkedResources", LinkedResources);
            writer.WriteObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.PatternedRecurrence>("recurrence", Recurrence);
            writer.WriteObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>("reminderDateTime", ReminderDateTime);
            writer.WriteObjectValue<global::GitHubTodoDemo.MicrosoftGraph.Models.DateTimeTimeZone>("startDateTime", StartDateTime);
            writer.WriteEnumValue<global::GitHubTodoDemo.MicrosoftGraph.Models.TaskStatus>("status", Status);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
