/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ListsRequestBuilderNavigationMetadata, ListsRequestBuilderRequestsMetadata, type ListsRequestBuilder } from './lists/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me/todo
 */
export interface TodoRequestBuilder extends BaseRequestBuilder<TodoRequestBuilder> {
    /**
     * Provides operations to manage the lists property of the microsoft.graph.todo entity.
     */
    get lists(): ListsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TodoRequestBuilderUriTemplate = "{+baseurl}/me/todo";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TodoRequestBuilderNavigationMetadata: Record<Exclude<keyof TodoRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    lists: {
        requestsMetadata: ListsRequestBuilderRequestsMetadata,
        navigationMetadata: ListsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
