// <auto-generated/>
using GitHubTodoDemo.MicrosoftGraph.Me.Todo.Lists;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHubTodoDemo.MicrosoftGraph.Me.Todo {
    /// <summary>
    /// Builds and executes requests for operations under \me\todo
    /// </summary>
    public class TodoRequestBuilder : BaseRequestBuilder {
        /// <summary>Provides operations to manage the lists property of the microsoft.graph.todo entity.</summary>
        public ListsRequestBuilder Lists { get =>
            new ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new TodoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TodoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/todo", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new TodoRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TodoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/todo", rawUrl) {
        }
    }
}
