using Microsoft.Kiota.Abstractions.Serialization;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
namespace GitHubTodoDemo.MicrosoftGraph.Models.Security {
    public class AnalyzedMessageEvidence : AlertEvidence, IParsable {
        /// <summary>Direction of the email relative to your network. The possible values are: inbound, outbound or intraorg.</summary>
        public string AntiSpamDirection { get; set; }
        /// <summary>Number of attachments in the email.</summary>
        public long? AttachmentsCount { get; set; }
        /// <summary>Delivery action of the email. The possible values are: delivered, deliveredAsSpam, junked, blocked, or replaced.</summary>
        public string DeliveryAction { get; set; }
        /// <summary>Location where the email was delivered. The possible values are: inbox, external, junkFolder, quarantine, failed, dropped, deletedFolder or forwarded.</summary>
        public string DeliveryLocation { get; set; }
        /// <summary>Public-facing identifier for the email that is set by the sending email system.</summary>
        public string InternetMessageId { get; set; }
        /// <summary>Detected language of the email content.</summary>
        public string Language { get; set; }
        /// <summary>Unique identifier for the email, generated by Microsoft 365.</summary>
        public string NetworkMessageId { get; set; }
        /// <summary>The P1 sender.</summary>
        public EmailSender P1Sender { get; set; }
        /// <summary>The P2 sender.</summary>
        public EmailSender P2Sender { get; set; }
        /// <summary>Date and time when the email was received.</summary>
        public DateTimeOffset? ReceivedDateTime { get; set; }
        /// <summary>Email address of the recipient, or email address of the recipient after distribution list expansion.</summary>
        public string RecipientEmailAddress { get; set; }
        /// <summary>IP address of the last detected mail server that relayed the message.</summary>
        public string SenderIp { get; set; }
        /// <summary>Subject of the email.</summary>
        public string Subject { get; set; }
        /// <summary>Collection of methods used to detect malware, phishing, or other threats found in the email.</summary>
        public List<string> ThreatDetectionMethods { get; set; }
        /// <summary>Collection of detection names for malware or other threats found.</summary>
        public List<string> Threats { get; set; }
        /// <summary>Number of embedded URLs in the email.</summary>
        public long? UrlCount { get; set; }
        /// <summary>Collection of the URLs contained in this email.</summary>
        public List<string> Urls { get; set; }
        /// <summary>Uniform resource name (URN) of the automated investigation where the cluster was identified.</summary>
        public string Urn { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new AnalyzedMessageEvidence CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new AnalyzedMessageEvidence();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public new IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers()) {
                {"antiSpamDirection", n => { AntiSpamDirection = n.GetStringValue(); } },
                {"attachmentsCount", n => { AttachmentsCount = n.GetLongValue(); } },
                {"deliveryAction", n => { DeliveryAction = n.GetStringValue(); } },
                {"deliveryLocation", n => { DeliveryLocation = n.GetStringValue(); } },
                {"internetMessageId", n => { InternetMessageId = n.GetStringValue(); } },
                {"language", n => { Language = n.GetStringValue(); } },
                {"networkMessageId", n => { NetworkMessageId = n.GetStringValue(); } },
                {"p1Sender", n => { P1Sender = n.GetObjectValue<EmailSender>(EmailSender.CreateFromDiscriminatorValue); } },
                {"p2Sender", n => { P2Sender = n.GetObjectValue<EmailSender>(EmailSender.CreateFromDiscriminatorValue); } },
                {"receivedDateTime", n => { ReceivedDateTime = n.GetDateTimeOffsetValue(); } },
                {"recipientEmailAddress", n => { RecipientEmailAddress = n.GetStringValue(); } },
                {"senderIp", n => { SenderIp = n.GetStringValue(); } },
                {"subject", n => { Subject = n.GetStringValue(); } },
                {"threatDetectionMethods", n => { ThreatDetectionMethods = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"threats", n => { Threats = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"urlCount", n => { UrlCount = n.GetLongValue(); } },
                {"urls", n => { Urls = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"urn", n => { Urn = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public new void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("antiSpamDirection", AntiSpamDirection);
            writer.WriteLongValue("attachmentsCount", AttachmentsCount);
            writer.WriteStringValue("deliveryAction", DeliveryAction);
            writer.WriteStringValue("deliveryLocation", DeliveryLocation);
            writer.WriteStringValue("internetMessageId", InternetMessageId);
            writer.WriteStringValue("language", Language);
            writer.WriteStringValue("networkMessageId", NetworkMessageId);
            writer.WriteObjectValue<EmailSender>("p1Sender", P1Sender);
            writer.WriteObjectValue<EmailSender>("p2Sender", P2Sender);
            writer.WriteDateTimeOffsetValue("receivedDateTime", ReceivedDateTime);
            writer.WriteStringValue("recipientEmailAddress", RecipientEmailAddress);
            writer.WriteStringValue("senderIp", SenderIp);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("threatDetectionMethods", ThreatDetectionMethods);
            writer.WriteCollectionOfPrimitiveValues<string>("threats", Threats);
            writer.WriteLongValue("urlCount", UrlCount);
            writer.WriteCollectionOfPrimitiveValues<string>("urls", Urls);
            writer.WriteStringValue("urn", Urn);
        }
    }
}
