# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'dotnet/**'
      - 'dotnet/*'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'dotnet/**'
      - 'dotnet/*'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: ./dotnet
      run: dotnet restore
    - name: Build
      working-directory: ./dotnet
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./dotnet
      run: dotnet test --no-build --verbosity normal
