# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        cache: true
        cache-dependency-path: dotnet/packages.lock.json
    - name: Restore dependencies
      working-directory: ./dotnet
      run: dotnet restore dotnet.sln
    - name: Build
      working-directory: ./dotnet
      run: dotnet build dotnet.sln --no-restore
    - name: Test
      working-directory: ./dotnet
      run: dotnet test dotnet.sln --no-build --verbosity normal
