name: Gradle Build And Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with: 
        java-version: 18
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: java
    - name: Build with Gradle
      run: ./gradlew --no-daemon build
      working-directory: java
