name: NodeJS build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-node@v4
      with: 
        node-version: 22
        cache: npm
    - name: Install dependencies
      run: npm ci
      working-directory: typescript
    - name: Build with Gradle
      run: npm run build
      working-directory: typescript